meta_title: "Take Away Trips"
meta_description: "Collect places, create your guides, and share with your friends"
meta_image: "home.jpg" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
