meta_title: "Take Away Trips"
meta_description: "Créez vos guides, collectez vos meilleures adresses et partagez-les avec vos amis"
meta_image: "home.png" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
